import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Open_Sans } from 'next/font/google'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { ModalProvider } from '@/components/providers/modal-provider'
import { SocketProvider } from '@/components/providers/socket-provider'
import { QueryProvider } from '@/components/providers/query-provider'

const inter = Inter({ subsets: ['latin'] })
const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressContentEditableWarning={true}>
        <body className={cn(font.className, "bg-white dark:bg-[#313338]")}>
          <SocketProvider>
            <ThemeProvider attribute='class'
              defaultTheme='dark'
              enableSystem={true}
              storageKey='discord-theme'
            >
              <ModalProvider />
                <QueryProvider>
              {children}
              </QueryProvider>
            </ThemeProvider>
          </SocketProvider>
        </body>
      </html>  
    </ClerkProvider>
  )
}
